
package airplanebookingsystem;

import javax.swing.JOptionPane;

public class UnbookASeat extends javax.swing.JFrame {

    
    AirplaneBookingSystem owner;
    
    
    public UnbookASeat(AirplaneBookingSystem owner) {
        this.owner = owner;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EnterSeatNumber = new javax.swing.JTextField();
        EnterName = new javax.swing.JTextField();
        EnterAge = new javax.swing.JTextField();
        UnbookSeat = new javax.swing.JButton();
        EnterPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Enter the Required Information in Order to Unbook a Seat");

        EnterSeatNumber.setText("  Enter Seat Number  ");

        EnterName.setText("     Enter Your Name    ");
        EnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNameActionPerformed(evt);
            }
        });

        EnterAge.setText("       Enter Your Age     ");
        EnterAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterAgeActionPerformed(evt);
            }
        });

        UnbookSeat.setText("Unbook This Seat");
        UnbookSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnbookSeatActionPerformed(evt);
            }
        });

        EnterPassword.setText("Enter Your Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnbookSeat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(EnterSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UnbookSeat)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterNameActionPerformed

    private void EnterAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterAgeActionPerformed

    private void UnbookSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnbookSeatActionPerformed
         int x=0;
        if (  Integer.parseInt(EnterSeatNumber.getText())>=0 && Integer.parseInt(EnterSeatNumber.getText())<200 && !owner.seats.get(Integer.parseInt(EnterSeatNumber.getText())).getAvailability()  ){
        //Seat number is good
        x++;
    }
        else{
            //Seat number does not exist or is not booked
           JOptionPane.showMessageDialog(null,"Seat number does not exist or seat has not been booked)","Problem!",JOptionPane.INFORMATION_MESSAGE);
       }
        if(Integer.parseInt(EnterAge.getText())>0){
            //age is good
            x++;
        }
        if(Integer.parseInt(EnterAge.getText())<=0){
            JOptionPane.showMessageDialog(null,"Age must be greater than 0","Problem!",JOptionPane.INFORMATION_MESSAGE);
        }
       
        if(!owner.seats.get(Integer.parseInt(EnterSeatNumber.getText())).getAvailability() && x==2){
          for(int k=0; k<owner.bookedseats.size(); k++){
              if(owner.bookedseats.get(k).getSeatIndexNumber()== Integer.parseInt(EnterSeatNumber.getText()) && owner.bookedseats.get(k).getName().equals(EnterName.getText()) && owner.bookedseats.get(k).getAge()==Integer.parseInt(EnterAge.getText()) && owner.bookedseats.get(k).getPassword().equals(EnterPassword.getText())){
        owner.bookedseats.remove(k);
        owner.seats.get(Integer.parseInt(EnterSeatNumber.getText())).setAvailability(true);
        JOptionPane.showMessageDialog(null,"Seat has been successfully unbooked!","Done!",JOptionPane.INFORMATION_MESSAGE);
              }
              else{
         JOptionPane.showMessageDialog(null,"One or More of the Entries You Made is Incorrect!","Problem!",JOptionPane.INFORMATION_MESSAGE);          
              }
             
          }

        }
    }//GEN-LAST:event_UnbookSeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnbookASeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnbookASeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnbookASeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnbookASeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnbookASeat(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnterAge;
    private javax.swing.JTextField EnterName;
    private javax.swing.JTextField EnterPassword;
    private javax.swing.JTextField EnterSeatNumber;
    private javax.swing.JButton UnbookSeat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
